services:
  mysql:
    build: .
    container_name: mysql-container
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      TZ: America/Sao_Paulo
    restart: always
